### ISSUE TITLE
sh: 2: Syntax error: ")" unexpected

### ISSUE THREAD

**Issue by krimtsev** [GubernievS/AntiZapret-VPN-Container#1]
![2024-08-08_15-16](https://github.com/user-attachments/assets/98933bde-dcfd-4ebd-8d3a-26baf6f87b51)

При установке есть какая-то синтетическая ошибка.

**Comment by raaad1on** [comment]
<img width="1038" alt="Снимок экрана 2024-08-08 в 19 40 55" src="https://github.com/user-attachments/assets/89729a26-095b-4bb2-80b4-3cca27734a58">

такая же проблема. 
ubuntu 22.04

вероятно из-за этого контейнер не разворачивается

**Comment by daemonpnz** [comment]
> такая же проблема. ubuntu 22.04
> 
> вероятно из-за этого контейнер не разворачивается

у вас проблема с dns на vps: failure name resolution

и пакеты не установились некоторые python3-pip и socat, например.

**Comment by GubernievS** [comment]
Ошибка со скобкой не влияла на установку и работу, просто не добавлялся AdGuard DNS, исправлено в версии 5.6
