### ISSUE TITLE
Поддержка Asus Wrt Merlin (предложение)

### ISSUE THREAD

**Issue by vbelevcev** [GubernievS/AntiZapret-VPN-Container#3]
Поддержка Asus Wrt Merlin (предложение)
Сделать аналогичный скрипт для роутеров Asus на прошивках Wrt Merlin
Я что-то не соображу правильно, да и очень многие думаю будут благодарны
Заранее спасибо

**Comment by GubernievS** [comment]
Это не скрипт на роутеры:)
